// Per-nationality name pools used by player generation (see
// engine/players.js). Each entry's `w` is a relative weight for
// engine/players.js's pickCountry — together they form a distribution
// loosely matching real NBA nationality demographics (~75% USA, with
// meaningful representation from the usual international pipelines and a
// long tail of one-or-two-player countries).
//
// `firstNames`/`lastNames` are flavor pools, not exhaustive; `cities` back
// the display-only birthplace field. None of this affects ratings.

export const NATIONALITIES = [
  {
    name: 'USA', flag: '🇺🇸', w: 750,
    firstNames: [
      'Jalen', 'Marcus', 'DeAndre', 'Tyrese', 'Cade', 'Darius', 'Malik', 'Jaylen', 'Zion', 'Trey',
      'Anthony', 'Devin', 'Isaiah', 'Jordan', 'Kevin', 'Chris', 'Mike', 'Aaron', 'Brandon', 'Cameron',
      'Damian', 'Elijah', 'Gary', 'Jamal', 'Keon', 'Lonnie', 'Miles', 'Omari', 'Paolo', 'Quentin',
      'Rashad', 'Scottie', 'Terrence', 'Victor', 'Wendell', 'Xavier', 'Zach', 'Andre', 'Caleb', 'Dejounte',
      'Evan', 'Fred', 'Herb', 'Immanuel', 'Josh', 'Kyle', 'Markelle', 'Nassir', 'Obi', 'Precious',
      'Quinn', 'RJ', 'Saddiq', 'Talen', 'Vince', 'Wesley', 'Ziaire', 'Amir', 'Cole', "Day'Ron",
      'Emoni', 'Jaden', 'Keegan', 'Lamar', 'Moses', 'Nigel', 'Patrick', 'Reggie', 'Shai', 'Tyler',
      'Donovan', 'Karl', 'Bradley', 'Tyus', "De'Aaron", "D'Angelo", 'Spencer', 'Jaylin', 'Jrue', 'Khris',
      'Norman', 'Royce', 'Terry', 'Tre', 'Tyrone', 'Wayne', 'Zaire', 'Brice', 'Cassius', 'Dyson',
      'Eric', 'Gabe', 'Grayson', 'Jericho', 'Kobe', 'Malachi', 'Nate', 'Oscar', 'Pete', 'Roman',
    ],
    lastNames: [
      'Williams', 'Johnson', 'Smith', 'Brown', 'Jones', 'Davis', 'Carter', 'Mitchell', 'Turner', 'Brooks',
      'Anderson', 'Bridges', 'Coleman', 'Edwards', 'Green', 'Harris', 'Ingram', 'Jackson', 'Knox', 'Lewis',
      'Murray', 'Porter', 'Quickley', 'Robinson', 'Thompson', 'Vassell', 'Washington', 'Young', 'Allen', 'Banchero',
      'Cunningham', 'Eubanks', 'Fox', 'Hayes', 'Ivey', 'Kispert', 'Livers', 'Primo', 'Reaves', 'Sharpe',
      'Tate', 'Umude', 'Vincent', 'Wagner', 'Ziegler', 'Adebayo', 'Barnes', 'Castle', 'Duarte', 'Eason',
      'Garland', 'Iverson', 'Jaquez', 'Kessler', 'Lively', 'Maxey', 'Nembhard', 'Oubre', 'Reed', 'Suggs',
      'Ware', 'Watson', 'Booker', 'Curry', 'Durant', 'Embry', 'Foster', 'Grant', 'Holiday', 'Irving',
      'James', 'Kelly', 'Lopez', 'Morant', 'Nunn', 'Owens', 'Parker', 'Quinn', 'Russell', 'Stewart',
      'Taylor', 'Underwood', 'Vanderbilt', 'Walker', 'Wright', 'Yates', 'Zubac', 'Bell', 'Collins', 'Dunn',
      'Ellis', 'Freeman', 'Graham', 'Hardaway', 'Isaacs', 'Jenkins', 'Kennard', 'Landry', 'Mills', 'Nance',
    ],
    cities: [
      'New York', 'Los Angeles', 'Chicago', 'Houston', 'Philadelphia', 'Atlanta', 'Detroit', 'Memphis',
      'New Orleans', 'Oakland', 'Baltimore', 'Cleveland', 'Dallas', 'Miami', 'Charlotte', 'Indianapolis',
      'Milwaukee', 'St. Louis', 'Brooklyn', 'Phoenix', 'Sacramento', 'Portland', 'Denver', 'Boston',
      'Seattle', 'Washington',
    ],
  },
  {
    name: 'Nigeria', flag: '🇳🇬', w: 30,
    firstNames: [
      'Chinedu', 'Emeka', 'Obinna', 'Chukwuma', 'Ikechukwu', 'Olumide', 'Adewale', 'Oluwaseun', 'Tobi', 'Tunde',
      'Femi', 'Ayodele', 'Kunle', 'Babatunde', 'Damilare', 'Chidi', 'Ifeanyi', 'Kelechi', 'Nnamdi', 'Uche',
      'Chibueze', 'Chukwuemeka', 'Onyeka', 'Ekene', 'Obiora', 'Chigozie', 'Chuka', 'Olufemi', 'Adebayo', 'Olusegun',
      'Akin', 'Bayo', 'Folarin', 'Gbenga', 'Wale', 'Yinka', 'Damola', 'Seun', 'Korede', 'Lekan',
      'Bashir', 'Suleiman', 'Aliyu', 'Yakubu', 'Ibrahim', 'Musa', 'Sani', 'Abdullahi', 'Garba', 'Nasir',
      'Chinaza', 'Kosi', 'Obadiah', 'Promise', 'Victor', 'Goodluck', 'Samuel', 'Daniel', 'Michael', 'Solomon',
      'Joseph', 'David', 'Praise', 'Divine', 'Success', 'Confidence', 'Blessing', 'Emmanuel', 'Anthony', 'Wisdom',
      'Frank', 'Vincent', 'Patrick', 'Stanley', 'Henry', 'Paul', 'Christian', 'Eric', 'Kennedy', 'Marvellous',
    ],
    lastNames: [
      'Okafor', 'Adeyemi', 'Okonkwo', 'Eze', 'Balogun', 'Abubakar', 'Nwosu', 'Okoye', 'Adebayo', 'Olawale',
      'Afolabi', 'Bello', 'Chukwu', 'Dike', 'Egwu', 'Falade', 'Gambo', 'Hassan', 'Ibekwe', 'Jegede',
      'Kalu', 'Lawal', 'Maduike', 'Nwankwo', 'Obi', 'Okoro', 'Oyelaran', 'Idowu', 'Quadri', 'Aremu',
      'Sanusi', 'Tijani', 'Uzo', 'Vincent', 'Williams', 'Yusuf', 'Zubair', 'Abiodun', 'Adeleke', 'Akinola',
      'Bakare', 'Chukwuma', 'Danjuma', 'Ekwueme', 'Fashola', 'Garuba', 'Husseini', 'Ikeazor', 'Jacobs', 'Kalejaiye',
      'Lasisi', 'Mohammed', 'Nnamdi', 'Obasanjo', 'Okeke', 'Onuoha', 'Peters', 'Raji', 'Salami', 'Tella',
      'Udo', 'Vanterpool', 'Wahab', 'Yakubu', 'Zara', 'Adeoye', 'Babangida', 'Chigozie', 'Dauda', 'Edochie',
      'Folashade', 'Gbadamosi', 'Haruna', 'Inyang', 'Joseph', 'Kanu', 'Mbah', 'Nwachukwu', 'Oduya', 'Sowunmi',
    ],
    cities: ['Lagos', 'Abuja', 'Kano', 'Ibadan', 'Port Harcourt', 'Benin City', 'Enugu', 'Kaduna', 'Jos', 'Owerri', 'Abeokuta', 'Onitsha', 'Warri', 'Calabar', 'Maiduguri'],
  },
  {
    name: 'France', flag: '🇫🇷', w: 28,
    firstNames: [
      'Étienne', 'Mathieu', 'Nicolas', 'Antoine', 'Théo', 'Hugo', 'Lucas', 'Thomas', 'Pierre', 'Jean',
      'Maxime', 'Julien', 'Romain', 'Baptiste', 'Quentin', 'Léo', 'Yanis', 'Adama', 'Ousmane', 'Moussa',
      'Mamadou', 'Karim', 'Sofiane', 'Bilal', 'Yannick', 'Cyril', 'Stéphane', 'Olivier', 'Sébastien', 'Damien',
      'Vincent', 'Florent', 'Guillaume', 'Loïc', 'Benjamin', 'Rudy', 'Frank', 'Killian', 'Evan', 'Timothé',
      'Mathis', 'Noah', 'Axel', 'Ilan', 'Wilfried', 'Cheikh', 'Souleymane', 'Ibrahima', 'Lassana', 'Boubacar',
      'Aboubakar', 'Modibo', 'Issa', 'Alpha', 'Idriss', 'Younes', 'Rayan', 'Nael', 'Gael', 'Joel',
      'Maxence', 'Clement', 'Florian', 'Tristan', 'Nathan', 'Enzo', 'Ethan', 'Bastien', 'Corentin', 'Valentin',
      'Yohann', 'Anthony', 'Jonathan', 'Steven', 'Kevin', 'David', 'Samuel', 'Gabriel', 'Raphael', 'Alexandre',
    ],
    lastNames: [
      'Dubois', 'Lefevre', 'Moreau', 'Girard', 'Bonnet', 'Fournier', 'Lambert', 'Rousseau', 'Mercier', 'Blanc',
      'Garnier', 'Faure', 'Roussel', 'Henry', 'Roy', 'Leroy', 'Gauthier', 'Perrin', 'Morel', 'Fontaine',
      'Chevalier', 'Robin', 'Masson', 'Sanchez', 'Gerard', 'Renard', 'Caron', 'Roux', 'Vidal', 'Picard',
      'Roche', 'Brun', 'Marchand', 'Joly', 'Aubert', 'Guerin', 'Boyer', 'Bertrand', 'Diallo', 'Traore',
      'Toure', 'Camara', 'Diarra', 'Ndiaye', 'Konate', 'Sangare', 'Fofana', 'Coulibaly', 'Keita', 'Diabate',
      'Sow', 'Cisse', 'Bah', 'Diakite', 'Ba', 'Kane', 'Doumbia', 'Mbaye', 'Marchetti', 'Lemoine',
      'Perrot', 'Charpentier', 'Bouvier', 'Renaud', 'Lacroix', 'Barbier', 'Dumas', 'Klein', 'Carpentier', 'Leclerc',
      'Fabre', 'Giraud', 'Andre', 'Lefebvre', 'Marie', 'Legrand', 'Garcia', 'David', 'Bertin', 'Renault',
    ],
    cities: ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Bordeaux', 'Lille', 'Rennes', 'Reims', 'Le Havre', 'Saint-Étienne', 'Toulon', 'Grenoble', 'Dijon'],
  },
  {
    name: 'Cameroon', flag: '🇨🇲', w: 18,
    firstNames: [
      'Joel', 'Pascal', 'Yves', 'Christian', 'Emmanuel', 'Junior', 'Franck', 'Patrick', 'Arnaud', 'Bertrand',
      'Cedric', 'Desire', 'Eric', 'Florent', 'Gaston', 'Herve', 'Innocent', 'Jacques', 'Kevin', 'Landry',
      'Marius', 'Narcisse', 'Olivier', 'Prince', 'Quentin', 'Raoul', 'Serge', 'Thierry', 'Ulrich', 'Valery',
      'Willy', 'Yannick', 'Achille', 'Brice', 'Cyrille', 'Donald', 'Edmond', 'Faustin', 'Gerald', 'Hilaire',
      'Ignace', 'Jean-Pierre', 'Leonel', 'Maxime', 'Norbert', 'Omer', 'Pacome', 'Robert', 'Samuel', 'Theodore',
      'Urbain', 'Vincent', 'Wilfried', 'Aurelien', 'Boris', 'Charly', 'Dieudonne', 'Elvis', 'Fabrice', 'Gilbert',
    ],
    lastNames: [
      'Mbeki', 'Ngoua', 'Fotso', 'Etoundi', 'Onana', 'Talla', 'Mballa', 'Biya', 'Ekambi', 'Nkoulou',
      'Etoo', 'Mbia', 'Song', 'Choupo', 'Anguissa', 'Ngamaleu', 'Mbenza', 'Toko', 'Bahoken', 'Banana',
      'Owona', 'Ngassam', 'Tchoukoua', 'Mvondo', 'Ze', 'Atangana', 'Essomba', 'Bekolo', 'Bissa', 'Ndongo',
      'Kemajou', 'Moukoko', 'Tchami', 'Nguema', 'Foe', 'Kana', 'Biyik', 'Manga', 'Tabe', 'Ekono',
      'Nkemta', 'Bayemi', 'Djoum', 'Eyenga', 'Fouda', 'Gouet', 'Hamani', 'Ipoua', 'Jiokeng', 'Kotto',
      'Lemvo', 'Maboang', 'Ndip', 'Oyono', 'Pondi', 'Tabi', 'Sango', 'Tene', 'Voundi', 'Wambo',
    ],
    cities: ['Douala', 'Yaoundé', 'Garoua', 'Bamenda', 'Maroua', 'Bafoussam', 'Ngaoundéré', 'Buea', 'Limbe', 'Kribi'],
  },
  {
    name: 'Australia', flag: '🇦🇺', w: 22,
    firstNames: [
      'Jock', 'Liam', 'Ryan', 'Matthew', 'Nathan', 'Joe', 'Ben', 'Dante', 'Jack', 'Cooper',
      'Lachlan', 'Hayden', 'Mitchell', 'Brock', 'Tyson', 'Bailey', 'Cody', 'Riley', 'Connor', 'Ethan',
      'Harrison', 'Jacob', 'Sam', 'Will', 'Tom', 'Dylan', 'Jordan', 'Aaron', 'Brendan', 'Cameron',
      'Daniel', 'Eli', 'Flynn', 'Gus', 'Harry', 'Isaac', 'Jett', 'Kane', 'Levi', 'Mason',
      'Noah', 'Owen', 'Patrick', 'Quinn', 'Reece', 'Seth', 'Toby', 'Wade', 'Zac', 'Angus',
      'Beau', 'Cale', 'Declan', 'Eamon', 'Finn', 'Grady', 'Hudson', 'Ira', 'Jaxon', 'Kyle',
      'Lewis', 'Marcus', 'Nash', 'Oscar', 'Pierce', 'Reuben', 'Spencer', 'Travis', 'Wyatt', 'Xander',
    ],
    lastNames: [
      'Wright', 'Hughes', 'Clarke', 'Walker', 'Mills', 'Baynes', 'Exum', 'Bogut', 'Smith', 'Brown',
      'Taylor', 'Wilson', 'White', 'Thompson', 'Martin', 'Edwards', 'Cooper', 'Foster', 'Bailey', 'Reid',
      'Murphy', 'Stevens', 'Hunter', 'Marshall', 'Webb', 'Simpson', 'Ross', 'Hamilton', 'Graham', 'Mason',
      'Ellis', 'Holland', 'Burns', 'Pearce', 'Lawson', 'Sutton', 'Newman', 'Chapman', 'Henderson', 'Gibson',
      'Black', 'Watt', 'Crowe', 'Doyle', 'Fraser', 'Glover', 'Hicks', 'Irwin', 'Jenkins', 'Kearns',
      'Larkin', 'Mackenzie', 'Nolan', "O'Brien", 'Parsons', 'Quill', 'Riley', 'Sanderson', 'Tindall', 'Underwood',
      'Vine', 'Ward', 'Yelland', 'Adamson', 'Bartlett', 'Curtis', 'Dwyer', 'Easton', 'Field', 'Gould',
    ],
    cities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Canberra', 'Newcastle', 'Hobart', 'Darwin'],
  },
  {
    name: 'Canada', flag: '🇨🇦', w: 22,
    firstNames: [
      'Tristan', 'Jamal', 'Cody', 'Andrew', 'Nickeil', 'Luguentz', 'Dwight', 'Kelly', 'Trey', 'Khem',
      'Chris', 'Cory', 'Brady', 'Tyler', 'Owen', 'Olivier', 'Mathieu', 'Simon', 'Felix', 'Gabriel',
      'Nathan', 'Noah', 'Ben', 'Caleb', 'Connor', 'Ethan', 'Logan', 'Mason', 'Carter', 'Lucas',
      'Liam', 'Aiden', 'Jacob', 'Wyatt', 'Hunter', 'Cole', 'Brandon', 'Justin', 'Mark', 'Sean',
      'Dominic', 'Maxime', 'Etienne', 'Antoine', 'Pascal', 'Vincent', 'Yannick', 'Andre', 'Pierre', 'Marcus',
      'Devin', 'Khalen', 'Quincy', 'Bennedict', 'Lindell', 'Emanuel', 'Mfiondu', 'Kyshawn', 'Zach', 'Thomas',
      'Phil', 'Steve', 'Greg', 'Eric', 'Travis', 'Dillon', 'Mychal', 'Dario', 'Trae', 'Reno',
    ],
    lastNames: [
      'Murray', 'Brooks', 'Alexander', 'Powell', 'Olynyk', 'Bennett', 'Brown', 'Wiggins', 'Joseph', 'Thomas',
      'Barrett', 'Hebert', 'Gauthier', 'Tremblay', 'Roy', 'Cote', 'Bouchard', 'Gagnon', 'Pelletier', 'Belanger',
      'Levesque', 'Morin', 'Ouellet', 'Lavoie', 'Fortin', 'Lefebvre', 'Gagne', 'Beaulieu', 'Boucher', 'Caron',
      'Dubois', 'Gauvin', 'Hamel', 'Lacroix', 'Marchand', 'Nadeau', 'Paquette', 'Richer', 'Simard', 'Tessier',
      'Vachon', 'Allard', 'Bergeron', 'Charron', 'Desjardins', 'Girard', 'Houle', 'Jolicoeur', 'Lapointe', 'Martel',
      'Noel', 'Ouimet', 'Page', 'Quintal', 'Roussel', 'Savard', 'Therrien', 'Vigneault', 'Walsh', 'Wright',
      'Young', 'Zima', 'Anderson', 'Baker', 'Carter', 'Davies', 'Ferguson', 'Grant', 'Hayward', 'Irwin',
    ],
    cities: ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Ottawa', 'Edmonton', 'Winnipeg', 'Quebec City', 'Hamilton', 'Mississauga'],
  },
  {
    name: 'Serbia', flag: '🇷🇸', w: 18,
    firstNames: [
      'Nikola', 'Bogdan', 'Vasilije', 'Dejan', 'Marko', 'Milos', 'Stefan', 'Aleksandar', 'Filip', 'Ognjen',
      'Vladimir', 'Nemanja', 'Dusan', 'Petar', 'Nenad', 'Goran', 'Zoran', 'Vuk', 'Borisav', 'Ivan',
      'Slobodan', 'Predrag', 'Branislav', 'Dragan', 'Miroslav', 'Radovan', 'Sinisa', 'Tomislav', 'Uros', 'Vladan',
      'Zarko', 'Aleksa', 'Bojan', 'Dimitrije', 'Edin', 'Igor', 'Jovan', 'Kosta', 'Lazar', 'Mihailo',
      'Nikolaj', 'Obrad', 'Pavle', 'Radoslav', 'Sava', 'Teodor', 'Veljko', 'Zivojin', 'Aco', 'Boban',
      'Cedomir', 'Dragoljub', 'Emir', 'Gavrilo', 'Ilija', 'Janko', 'Krsto', 'Ljubomir', 'Mladen', 'Nebojsa',
      'Ratko', 'Strahinja', 'Trifun', 'Velimir', 'Zarije', 'Andrija', 'Branko', 'Cvetin', 'Darko', 'Djordje',
    ],
    lastNames: [
      'Petrovic', 'Stojakovic', 'Vucevic', 'Bjelica', 'Jovanovic', 'Markovic', 'Nikolic', 'Stankovic', 'Ilic', 'Pavlovic',
      'Djordjevic', 'Simic', 'Kovacevic', 'Popovic', 'Ristic', 'Tomic', 'Milosevic', 'Jankovic', 'Maric', 'Radovic',
      'Stojanovic', 'Antic', 'Vasic', 'Filipovic', 'Mitrovic', 'Lazic', 'Stevanovic', 'Gajic', 'Radulovic', 'Vukovic',
      'Cvetkovic', 'Dimitrijevic', 'Eric', 'Ivanovic', 'Jevtic', 'Knezevic', 'Lukic', 'Matic', 'Nedeljkovic', 'Obradovic',
      'Pejic', 'Radic', 'Savic', 'Todorovic', 'Uskokovic', 'Vidovic', 'Zivkovic', 'Adamovic', 'Bajic', 'Cosic',
      'Despotovic', 'Filipovski', 'Gavrilovic', 'Hadzic', 'Ivkovic', 'Jovicic', 'Kostic', 'Lukovic', 'Mihajlovic', 'Nikic',
      'Ostojic', 'Perisic', 'Radonjic', 'Sekulic', 'Tasic', 'Urosevic', 'Vujicic', 'Zarkovic', 'Bogdanovic', 'Krstic',
    ],
    cities: ['Belgrade', 'Novi Sad', 'Niš', 'Kragujevac', 'Subotica', 'Zrenjanin', 'Pančevo', 'Čačak', 'Kraljevo', 'Smederevo'],
  },
  {
    name: 'Germany', flag: '🇩🇪', w: 18,
    firstNames: [
      'Dennis', 'Maximilian', 'Franz', 'Daniel', 'Moritz', 'Paul', 'Tristan', 'Lukas', 'Jonas', 'Niklas',
      'Florian', 'Sebastian', 'Tobias', 'Felix', 'Julian', 'Leon', 'Marvin', 'Tim', 'Jan', 'Marcel',
      'Christoph', 'Andreas', 'Stefan', 'Thomas', 'Michael', 'Markus', 'Matthias', 'Patrick', 'Robert', 'Alexander',
      'Benjamin', 'David', 'Simon', 'Erik', 'Fabian', 'Henrik', 'Joachim', 'Karsten', 'Lars', 'Maik',
      'Nico', 'Oliver', 'Philipp', 'Quirin', 'Rene', 'Sven', 'Till', 'Uwe', 'Volker', 'Wolfgang',
      'Adrian', 'Bastian', 'Christian', 'Dominik', 'Emil', 'Frederik', 'Gerhard', 'Hannes', 'Ingo', 'Jens',
      'Klaus', 'Lennart', 'Manuel', 'Norbert', 'Otto', 'Peter', 'Quentin', 'Rainer', 'Sascha', 'Torben',
      'Ulrich', 'Viktor', 'Wilhelm', 'Yannick', 'Aaron', 'Bjoern', 'Cedric', 'Detlef', 'Eugen', 'Falk',
    ],
    lastNames: [
      'Schröder', 'Wagner', 'Theis', 'Hartenstein', 'Müller', 'Schmidt', 'Schneider', 'Fischer', 'Weber', 'Meyer',
      'Becker', 'Schulz', 'Hoffmann', 'Koch', 'Richter', 'Klein', 'Wolf', 'Schroeder', 'Neumann', 'Schwarz',
      'Zimmermann', 'Braun', 'Krüger', 'Hofmann', 'Hartmann', 'Lange', 'Werner', 'Schmitt', 'Krause', 'Meier',
      'Lehmann', 'Schmid', 'Schubert', 'Maier', 'Vogel', 'Friedrich', 'Keller', 'Günther', 'Frank', 'Berger',
      'Winkler', 'Roth', 'Beck', 'Lorenz', 'Baumann', 'Franke', 'Albrecht', 'Schuster', 'Simon', 'Ludwig',
      'Böhm', 'Winter', 'Kaiser', 'Fuchs', 'Peters', 'Lang', 'Scholz', 'Möller', 'Weiss', 'Jung',
      'Hahn', 'Schreiber', 'Graf', 'Heinrich', 'Brandt', 'Krieger', 'Schäfer', 'Vogt', 'Sauer', 'Engel',
      'Wenzel', 'Pfeiffer', 'Horn', 'Walter', 'Krämer', 'Huber', 'Kraus', 'Pohl', 'Sommer', 'Dietrich',
    ],
    cities: ['Berlin', 'Munich', 'Hamburg', 'Cologne', 'Frankfurt', 'Stuttgart', 'Düsseldorf', 'Dortmund', 'Leipzig', 'Bremen'],
  },
  {
    name: 'Slovenia', flag: '🇸🇮', w: 14,
    firstNames: [
      'Luka', 'Klemen', 'Edo', 'Jaka', 'Zan', 'Gregor', 'Vlatko', 'Aleksej', 'Miha', 'Rok',
      'Tilen', 'Matic', 'Domen', 'Tadej', 'Anze', 'Blaz', 'Crt', 'Erik', 'Filip', 'Gasper',
      'Ivan', 'Jure', 'Kristjan', 'Leon', 'Marko', 'Nejc', 'Ozren', 'Primoz', 'Robert', 'Sasa',
      'Tomaz', 'Uros', 'Vid', 'Zoran', 'Andraz', 'Bostjan', 'Ciril', 'David', 'Enej', 'Fabjan',
      'Gal', 'Hugo', 'Igor', 'Janez', 'Kristian', 'Lovro', 'Maks', 'Niko', 'Ostoj', 'Patrik',
      'Rene', 'Simon', 'Timotej', 'Urban', 'Valentin', 'Ziga', 'Adam', 'Borut', 'Crtomir', 'Dejan',
    ],
    lastNames: [
      'Novak', 'Horvat', 'Kovacic', 'Zupan', 'Krajnc', 'Potocnik', 'Vidmar', 'Kos', 'Golob', 'Music',
      'Mlakar', 'Tomsic', 'Skubic', 'Vodnik', 'Pavlin', 'Rozman', 'Sever', 'Korosec', 'Hribar', 'Pirc',
      'Zagar', 'Cerar', 'Klemencic', 'Sustar', 'Bevc', 'Cvelbar', 'Dolenc', 'Erjavec', 'Frelih', 'Gorisek',
      'Hrovat', 'Jereb', 'Kastelic', 'Lah', 'Mihelic', 'Oblak', 'Pucnik', 'Radej', 'Skerbinc', 'Strgar',
      'Trost', 'Valant', 'Volk', 'Zalar', 'Bajc', 'Cuk', 'Drnovsek', 'Globocnik', 'Jelovcan', 'Kunc',
      'Lapuh', 'Marn', 'Nared', 'Ostrelic', 'Persak', 'Resnik', 'Smolnikar', 'Tominc', 'Urbanc', 'Vrabic',
    ],
    cities: ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Koper', 'Novo Mesto', 'Velenje', 'Ptuj', 'Trbovlje', 'Murska Sobota'],
  },
  {
    name: 'Spain', flag: '🇪🇸', w: 14,
    firstNames: [
      'Pau', 'Marc', 'Ricky', 'Sergio', 'Juancho', 'Santi', 'Alex', 'Victor', 'Willy', 'Jose',
      'Javier', 'Carlos', 'Manuel', 'David', 'Daniel', 'Antonio', 'Pedro', 'Miguel', 'Francisco', 'Juan',
      'Alvaro', 'Diego', 'Adrian', 'Pablo', 'Raul', 'Hugo', 'Ivan', 'Mario', 'Ruben', 'Fernando',
      'Rafael', 'Jorge', 'Gonzalo', 'Eduardo', 'Enrique', 'Roberto', 'Angel', 'Joaquin', 'Cesar', 'Andres',
      'Lorenzo', 'Marcos', 'Tomas', 'Salvador', 'Vicente', 'Emilio', 'Felipe', 'Gabriel', 'Ignacio', 'Julio',
      'Lucas', 'Mateo', 'Nicolas', 'Oscar', 'Pascual', 'Quim', 'Rodrigo', 'Samuel', 'Teodoro', 'Urbano',
      'Valentin', 'Xavi', 'Yago', 'Zacarias', 'Agustin', 'Bautista', 'Cristian', 'Dario', 'Esteban', 'Fabio',
      'Gerard', 'Hector', 'Inigo', 'Jaime', 'Kiko', 'Leandro', 'Martin', 'Nestor', 'Octavio', 'Pol',
    ],
    lastNames: [
      'Fernandez', 'Garcia', 'Lopez', 'Martinez', 'Rodriguez', 'Hernandez', 'Gomez', 'Diaz', 'Alvarez', 'Moreno',
      'Munoz', 'Romero', 'Alonso', 'Gutierrez', 'Navarro', 'Torres', 'Dominguez', 'Vazquez', 'Ramos', 'Gil',
      'Ramirez', 'Serrano', 'Blanco', 'Molina', 'Morales', 'Suarez', 'Ortega', 'Delgado', 'Castro', 'Ortiz',
      'Rubio', 'Marin', 'Sanz', 'Nunez', 'Iglesias', 'Medina', 'Garrido', 'Cortes', 'Castillo', 'Santos',
      'Lozano', 'Guerrero', 'Cano', 'Prieto', 'Mendez', 'Cruz', 'Calvo', 'Gallego', 'Vidal', 'Leon',
      'Herrera', 'Marquez', 'Pena', 'Flores', 'Cabrera', 'Campos', 'Vega', 'Fuentes', 'Carrasco', 'Diez',
      'Caballero', 'Reyes', 'Nieto', 'Aguilar', 'Pascual', 'Herrero', 'Santana', 'Lorenzo', 'Montero', 'Hidalgo',
      'Giminez', 'Ibanez', 'Ferrer', 'Vicente', 'Soto', 'Duran', 'Velazquez', 'Pastor', 'Sancho', 'Roca',
    ],
    cities: ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Bilbao', 'Murcia', 'Palma', 'Las Palmas'],
  },
  {
    name: 'Brazil', flag: '🇧🇷', w: 14,
    firstNames: [
      'Leo', 'Bruno', 'Yago', 'Vitor', 'Lucas', 'Gui', 'Anderson', 'Joao', 'Pedro', 'Gabriel',
      'Rafael', 'Felipe', 'Thiago', 'Marcelo', 'Fernando', 'Eduardo', 'Diego', 'Caio', 'Igor', 'Rodrigo',
      'Renato', 'Andre', 'Cesar', 'Daniel', 'Henrique', 'Vinicius', 'Murilo', 'Otavio', 'Paulo', 'Ricardo',
      'Sergio', 'Tiago', 'Ubiratan', 'Victor', 'William', 'Yuri', 'Zeca', 'Alessandro', 'Breno', 'Cristiano',
      'Davi', 'Emerson', 'Fabio', 'Gustavo', 'Heitor', 'Italo', 'Jefferson', 'Kaique', 'Leonardo', 'Mateus',
      'Nicolas', 'Osvaldo', 'Pablo', 'Raimundo', 'Samuel', 'Tales', 'Ulisses', 'Valdir', 'Wagner', 'Xande',
      'Antonio', 'Benicio', 'Claudio', 'Douglas', 'Elias', 'Flavio', 'Geraldo', 'Helio', 'Ivo', 'Jorge',
      'Kleber', 'Lucio', 'Marcio', 'Nelson', 'Oziel', 'Plinio', 'Quintino', 'Robson', 'Tarcisio', 'Uendel',
    ],
    lastNames: [
      'Silva', 'Santos', 'Oliveira', 'Souza', 'Costa', 'Pereira', 'Almeida', 'Ferreira', 'Rodrigues', 'Carvalho',
      'Gomes', 'Martins', 'Araujo', 'Melo', 'Barros', 'Ribeiro', 'Cardoso', 'Nascimento', 'Lima', 'Moreira',
      'Teixeira', 'Correia', 'Mendes', 'Nunes', 'Soares', 'Vieira', 'Monteiro', 'Cavalcanti', 'Dias', 'Castro',
      'Campos', 'Cunha', 'Pinto', 'Freitas', 'Andrade', 'Azevedo', 'Machado', 'Rocha', 'Reis', 'Brito',
      'Pires', 'Tavares', 'Borges', 'Fonseca', 'Lopes', 'Marques', 'Antunes', 'Coelho', 'Duarte', 'Esteves',
      'Farias', 'Guimaraes', 'Henriques', 'Junqueira', 'Leite', 'Macedo', 'Neves', 'Paiva', 'Queiroz', 'Ramalho',
      'Sales', 'Toledo', 'Uchoa', 'Valadares', 'Wanderley', 'Xavier', 'Zanetti', 'Amaral', 'Bezerra', 'Caldeira',
      'Justino', 'Klaus', 'Loureiro', 'Mariano', 'Nogueira', 'Ottoni', 'Peixoto', 'Quirino', 'Rezende', 'Siqueira',
    ],
    cities: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Porto Alegre'],
  },
  {
    name: 'Greece', flag: '🇬🇷', w: 10,
    firstNames: [
      'Giannis', 'Thanasis', 'Kostas', 'Vassilis', 'Nikos', 'Dimitris', 'Georgios', 'Alexandros', 'Christos', 'Yannis',
      'Panagiotis', 'Apostolos', 'Stavros', 'Ioannis', 'Spyros', 'Theodoros', 'Michalis', 'Andreas', 'Petros', 'Antonis',
      'Manolis', 'Stelios', 'Leonidas', 'Aris', 'Achilleas', 'Dionysios', 'Evangelos', 'Filippos', 'Grigoris', 'Harilaos',
      'Iraklis', 'Kyriakos', 'Lefteris', 'Marios', 'Nestoras', 'Odysseas', 'Pavlos', 'Sotiris', 'Telis', 'Vangelis',
      'Zisis', 'Argyris', 'Babis', 'Charalambos', 'Diamantis', 'Efthimios', 'Foivos', 'Gerasimos', 'Haris', 'Ilias',
      'Konstantinos', 'Lazaros', 'Makis', 'Nikolaos', 'Orestis', 'Periklis', 'Renos', 'Savvas', 'Triantafyllos', 'Valantis',
    ],
    lastNames: [
      'Papadopoulos', 'Papadakis', 'Nikolaidis', 'Karagiannis', 'Antoniou', 'Vasileiou', 'Georgiou', 'Dimitriou', 'Konstantinou', 'Ioannidis',
      'Pappas', 'Athanasiou', 'Christodoulou', 'Stavrou', 'Michaelidis', 'Petrou', 'Andreou', 'Theodorou', 'Spyridon', 'Lambros',
      'Markou', 'Nastos', 'Oikonomou', 'Panagiotou', 'Roussos', 'Sakellariou', 'Tsakiris', 'Vlachos', 'Xenakis', 'Zografos',
      'Adamopoulos', 'Bouras', 'Chatzis', 'Dellis', 'Efstathiou', 'Fragkos', 'Galanis', 'Hatzis', 'Iordanidis', 'Kazantzis',
      'Liakos', 'Margaritis', 'Nikas', 'Orfanos', 'Pavlidis', 'Rallis', 'Sotiriou', 'Tzortzis', 'Vavalis', 'Yannakopoulos',
      'Zervas', 'Anastasiou', 'Bekas', 'Charisis', 'Drakos', 'Eleftheriou', 'Fotiou', 'Gerakaris', 'Hadjis', 'Ikonomou',
    ],
    cities: ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa', 'Volos', 'Ioannina', 'Kavala', 'Chania', 'Rhodes'],
  },
  {
    name: 'Turkey', flag: '🇹🇷', w: 10,
    firstNames: [
      'Cedi', 'Furkan', 'Ersan', 'Alperen', 'Omer', 'Sertac', 'Cem', 'Berk', 'Mert', 'Emre',
      'Burak', 'Caner', 'Doruk', 'Eren', 'Faruk', 'Gokhan', 'Hakan', 'Ilker', 'Kaan', 'Levent',
      'Murat', 'Nuri', 'Onur', 'Polat', 'Recep', 'Selim', 'Tarik', 'Ufuk', 'Volkan', 'Yasin',
      'Zafer', 'Ahmet', 'Baris', 'Cengiz', 'Deniz', 'Erdem', 'Fatih', 'Gurkan', 'Halil', 'Ismail',
      'Kerem', 'Mehmet', 'Necati', 'Okan', 'Rauf', 'Sinan', 'Taner', 'Umut', 'Veli', 'Yusuf',
      'Bora', 'Can', 'Demir', 'Engin', 'Fikret', 'Gurcan', 'Hasan', 'Ibrahim', 'Kadir', 'Lokman',
    ],
    lastNames: [
      'Yilmaz', 'Kaya', 'Demir', 'Sahin', 'Celik', 'Yildiz', 'Yildirim', 'Ozturk', 'Aydin', 'Ozdemir',
      'Arslan', 'Dogan', 'Kilic', 'Aslan', 'Cetin', 'Kara', 'Koc', 'Kurt', 'Ozkan', 'Simsek',
      'Tas', 'Aydogan', 'Bozkurt', 'Cinar', 'Duman', 'Erdogan', 'Filiz', 'Guler', 'Han', 'Inan',
      'Kaplan', 'Kocak', 'Mutlu', 'Nalbant', 'Ozer', 'Saglam', 'Tekin', 'Ulu', 'Vural', 'Yavuz',
      'Akin', 'Baran', 'Coban', 'Demirel', 'Ergin', 'Gunes', 'Hamza', 'Ipek', 'Karaca', 'Korkmaz',
      'Ozkaya', 'Sezer', 'Tunc', 'Uysal', 'Yalcin', 'Akman', 'Balci', 'Cakir', 'Demirtas', 'Polat',
    ],
    cities: ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya', 'Adana', 'Gaziantep', 'Konya', 'Mersin', 'Eskişehir'],
  },
  {
    name: 'Latvia', flag: '🇱🇻', w: 8,
    firstNames: [
      'Kristaps', 'Davis', 'Rodions', 'Janis', 'Arturs', 'Roberts', 'Edgars', 'Toms', 'Reinis', 'Karlis',
      'Martins', 'Mareks', 'Andris', 'Girts', 'Valters', 'Ralfs', 'Niks', 'Oskars', 'Peteris', 'Raivis',
      'Sandis', 'Tomass', 'Uldis', 'Viesturs', 'Aivars', 'Brencis', 'Cernis', 'Dainis', 'Edvins', 'Felikss',
      'Gatis', 'Henrijs', 'Ivars', 'Jurgis', 'Klavs', 'Laimonis', 'Madars', 'Normunds', 'Olafs', 'Pauls',
      'Rihards', 'Sergejs', 'Talis', 'Uvis', 'Vilnis', 'Zigmunds', 'Ainars', 'Bruno', 'Egils', 'Ilmars',
    ],
    lastNames: [
      'Ozols', 'Kalnins', 'Berzins', 'Liepins', 'Krastins', 'Eglitis', 'Vitols', 'Zarins', 'Balodis', 'Petersons',
      'Jansons', 'Kaminskis', 'Lapins', 'Mezis', 'Niedra', 'Osis', 'Priede', 'Rozentals', 'Saulitis', 'Tomsons',
      'Upitis', 'Vanags', 'Zvaigzne', 'Andersons', 'Bergmanis', 'Cirulis', 'Dzenis', 'Endzelins', 'Freibergs', 'Gulbis',
      'Hofmanis', 'Ivanovs', 'Jakobsons', 'Klavins', 'Lazdans', 'Melnalksnis', 'Niklasons', 'Ositis', 'Plostnieks', 'Riekstins',
      'Sietins', 'Trukans', 'Urbans', 'Vilkins', 'Zaicevs', 'Apsitis', 'Bukss', 'Celms', 'Dauge', 'Eberhards',
    ],
    cities: ['Riga', 'Daugavpils', 'Liepāja', 'Jelgava', 'Jūrmala', 'Ventspils', 'Rēzekne', 'Valmiera', 'Ogre', 'Cēsis'],
  },
  {
    name: 'South Sudan', flag: '🇸🇸', w: 6,
    firstNames: [
      'Bol', 'Wenyen', 'Nuni', 'Khaman', 'Carlik', 'Makur', 'Wenin', 'Ater', 'Bul', 'Chol',
      'Deng', 'Garang', 'Akoy', 'Mayen', 'Nyok', 'Awer', 'Biel', 'Chuol', 'Dut', 'Gai',
      'Jok', 'Kuek', 'Lual', 'Majak', 'Nhial', 'Pal', 'Reec', 'Thon', 'Wal', 'Yel',
      'Abuk', 'Ayuel', 'Bona', 'Choul', 'Dau', 'Gatkek', 'Goch', 'Kueth', 'Lam', 'Manyok',
      'Nyuon', 'Oyat', 'Pach', 'Riak', 'Tong', 'Yach', 'Aleu', 'Apuk', 'Awan', 'Beny',
    ],
    lastNames: [
      'Maker', 'Akech', 'Wek', 'Achiek', 'Awak', 'Bany', 'Chiek', 'Dak', 'Duop', 'Gatluak',
      'Gum', 'Jal', 'Kiir', 'Lueth', 'Madut', 'Malek', 'Mayom', 'Nyiel', 'Padiet', 'Riek',
      'Tutdel', 'Ujang', 'Wani', 'Yak', 'Abiel', 'Achuoth', 'Agok', 'Ajak', 'Anei', 'Bith',
      'Buay', 'Dhal', 'Gak', 'Jiel', 'Kuol', 'Lat', 'Loro', 'Marial', 'Ngor', 'Puok',
      'Rin', 'Tuong', 'Wun', 'Yiep', 'Aciek', 'Bek', 'Cuany', 'Diing', 'Gony', 'Jock',
    ],
    cities: ['Juba', 'Wau', 'Malakal', 'Yei', 'Bor', 'Aweil', 'Rumbek', 'Bentiu', 'Torit', 'Yambio'],
  },
  // --- small catch-all for everywhere else: a long tail of one-or-two
  // player countries, each with a slim name pool of its own.
  {
    name: 'Lithuania', flag: '🇱🇹', w: 2,
    firstNames: ['Jonas', 'Mindaugas', 'Domantas', 'Donatas', 'Arnas', 'Rokas', 'Tadas', 'Mantas', 'Marius', 'Vytenis', 'Linas', 'Edvinas', 'Gytis', 'Ignas', 'Karolis', 'Lukas', 'Nerijus', 'Paulius', 'Rimas', 'Saulius'],
    lastNames: ['Kazlauskas', 'Petrauskas', 'Jankauskas', 'Vasiliauskas', 'Stankevicius', 'Butkus', 'Adomaitis', 'Bartkus', 'Cesnauskas', 'Daugirdas', 'Eidukas', 'Gudaitis', 'Ivanauskas', 'Jocius', 'Kuzmickas', 'Liepa', 'Mockus', 'Norkus', 'Paulauskas', 'Raulinaitis'],
    cities: ['Vilnius', 'Kaunas', 'Klaipėda', 'Šiauliai', 'Panevėžys'],
  },
  {
    name: 'Croatia', flag: '🇭🇷', w: 2,
    firstNames: ['Ivan', 'Marko', 'Ante', 'Mario', 'Tomislav', 'Dario', 'Zoran', 'Stipe', 'Filip', 'Bruno', 'Domagoj', 'Josip', 'Krunoslav', 'Leon', 'Niko', 'Petar', 'Roko', 'Sime', 'Tin', 'Vedran'],
    lastNames: ['Jurkovic', 'Kovac', 'Maric', 'Pavic', 'Rados', 'Sabljic', 'Tomasevic', 'Vukic', 'Zubac', 'Andric', 'Brkic', 'Cvitanovic', 'Delic', 'Franjic', 'Galic', 'Halilovic', 'Ivancic', 'Juric', 'Klaric', 'Lovric'],
    cities: ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar'],
  },
  {
    name: 'Italy', flag: '🇮🇹', w: 2,
    firstNames: ['Marco', 'Luca', 'Andrea', 'Matteo', 'Davide', 'Simone', 'Alessandro', 'Federico', 'Lorenzo', 'Riccardo', 'Giovanni', 'Stefano', 'Paolo', 'Niccolo', 'Gianmarco', 'Danilo', 'Nicolo', 'Amedeo', 'Achille', 'Vittorio'],
    lastNames: ['Rossi', 'Russo', 'Ferrari', 'Esposito', 'Bianchi', 'Romano', 'Colombo', 'Ricci', 'Marino', 'Greco', 'Bruno', 'Gallo', 'Conti', 'De Luca', 'Mancini', 'Costa', 'Giordano', 'Rizzo', 'Lombardi', 'Moretti'],
    cities: ['Rome', 'Milan', 'Naples', 'Turin', 'Bologna'],
  },
  {
    name: 'Argentina', flag: '🇦🇷', w: 2,
    firstNames: ['Manu', 'Luis', 'Facundo', 'Nicolas', 'Gabriel', 'Patricio', 'Leandro', 'Marcos', 'Tomas', 'Santiago', 'Agustin', 'Bruno', 'Ezequiel', 'Federico', 'Gonzalo', 'Ivan', 'Joaquin', 'Lautaro', 'Matias', 'Nahuel'],
    lastNames: ['Gonzalez', 'Rodriguez', 'Fernandez', 'Lopez', 'Martinez', 'Garcia', 'Perez', 'Sanchez', 'Romero', 'Gomez', 'Diaz', 'Acosta', 'Benitez', 'Campos', 'Duarte', 'Flores', 'Herrera', 'Juarez', 'Medina', 'Ortiz'],
    cities: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata'],
  },
  {
    name: 'Dominican Republic', flag: '🇩🇴', w: 2,
    firstNames: ['Juan', 'Carlos', 'Luis', 'Jose', 'Manuel', 'Rafael', 'Pedro', 'Felix', 'Yoel', 'Yermin', 'Wander', 'Junior', 'Elvis', 'Frank', 'Ramon', 'Ruben', 'Santo', 'Tirso', 'Wilmer', 'Yefri'],
    lastNames: ['Reyes', 'Mendez', 'Mercedes', 'Polanco', 'Severino', 'Pena', 'De Leon', 'Guerrero', 'Tavarez', 'Familia', 'Sanchez', 'Soto', 'Castillo', 'Vargas', 'Cabrera', 'Paulino', 'Rosario', 'Tejada', 'Encarnacion', 'Liriano'],
    cities: ['Santo Domingo', 'Santiago', 'La Romana', 'San Pedro de Macorís', 'Puerto Plata'],
  },
  {
    name: 'Senegal', flag: '🇸🇳', w: 2,
    firstNames: ['Modibo', 'Cheikh', 'Mamadou', 'Mansour', 'Maurice', 'Ibrahima', 'Babacar', 'Pape', 'Gorgui', 'Boniface', 'Birame', 'Saer', 'Mbaye', 'Khalil', 'Ngagne', 'Tacko', 'Souleymane', 'Aliou', 'Demba', 'Idrissa'],
    lastNames: ['Ndiaye', 'Diop', 'Gueye', 'Faye', 'Diouf', 'Sarr', 'Toure', 'Camara', 'Sy', 'Diagne', 'Sow', 'Mbaye', 'Niang', 'Fall', 'Sene', 'Thiam', 'Ba', 'Lo', 'Kane', 'Diallo'],
    cities: ['Dakar', 'Touba', 'Thiès', 'Rufisque', 'Saint-Louis'],
  },
  {
    name: 'Bahamas', flag: '🇧🇸', w: 1,
    firstNames: ['Buddy', 'Deandre', 'Eric', 'Kevarrius', 'Trevon', 'Norman', 'Jonathan', 'Ariel', 'Travis', 'Antoan', 'Dario', 'Mychal', 'Lacy', 'Wendell', 'Tyrone', 'Reginald', 'Cory', 'Devon', 'Roger', 'Marvin'],
    lastNames: ['Adderley', 'Rolle', 'Munnings', 'Hanna', 'Russell', 'Smith', 'Bonaby', 'Knowles', 'Stuart', 'Forbes', 'Bethel', 'Cartwright', 'Burrows', 'Pratt', 'Symonette', 'Curry', 'Dean', 'Ferguson', 'Gibson', 'Hepburn'],
    cities: ['Nassau', 'Freeport', 'West End', 'Marsh Harbour'],
  },
  {
    name: 'Japan', flag: '🇯🇵', w: 1,
    firstNames: ['Yuta', 'Rui', 'Yuki', 'Hiroshi', 'Kenji', 'Takashi', 'Daiki', 'Ryo', 'Kaito', 'Sho', 'Haruto', 'Akira', 'Sota', 'Riku', 'Yamato', 'Hayato', 'Naoki', 'Ren', 'Tatsuya', 'Yusuke'],
    lastNames: ['Watanabe', 'Tanaka', 'Suzuki', 'Takahashi', 'Ito', 'Yamamoto', 'Nakamura', 'Kobayashi', 'Saito', 'Kato', 'Yoshida', 'Yamada', 'Sasaki', 'Yamaguchi', 'Matsumoto', 'Inoue', 'Kimura', 'Hayashi', 'Shimizu', 'Mori'],
    cities: ['Tokyo', 'Osaka', 'Nagoya', 'Yokohama', 'Sapporo'],
  },
  {
    name: 'Georgia', flag: '🇬🇪', w: 1,
    firstNames: ['Goga', 'Tornike', 'Giorgi', 'Levan', 'Nika', 'Davit', 'Beka', 'Luka', 'Saba', 'Mamuka', 'Zviad', 'Irakli', 'Otar', 'Vato', 'Lasha', 'Archil', 'Gigi', 'Temur', 'Shota', 'Vakhtang'],
    lastNames: ['Kvirkvelia', 'Antadze', 'Tsintsadze', 'Pruidze', 'Bochorishvili', 'Mamuladze', 'Chkheidze', 'Davitashvili', 'Gelashvili', 'Kapanadze', 'Lomidze', 'Maisuradze', 'Nadiradze', 'Okriashvili', 'Papidze', 'Robakidze', 'Sharikadze', 'Tabagari', 'Vashakidze', 'Zhordania'],
    cities: ['Tbilisi', 'Batumi', 'Kutaisi', 'Rustavi'],
  },
  {
    name: 'Finland', flag: '🇫🇮', w: 1,
    firstNames: ['Lauri', 'Mikael', 'Sasu', 'Elias', 'Mikko', 'Antti', 'Juho', 'Kalle', 'Niko', 'Olli', 'Pekka', 'Risto', 'Sami', 'Tapio', 'Veli', 'Aleksi', 'Eero', 'Heikki', 'Ilari', 'Joonas'],
    lastNames: ['Korhonen', 'Virtanen', 'Makinen', 'Nieminen', 'Makela', 'Hamalainen', 'Laine', 'Heikkinen', 'Koskinen', 'Jarvinen', 'Lehtonen', 'Lehtinen', 'Saarinen', 'Salminen', 'Heinonen', 'Niemi', 'Heikkila', 'Kinnunen', 'Salo', 'Turunen'],
    cities: ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu'],
  },
  {
    name: 'Egypt', flag: '🇪🇬', w: 1,
    firstNames: ['Ahmed', 'Mohamed', 'Omar', 'Mahmoud', 'Khaled', 'Karim', 'Tarek', 'Hossam', 'Amr', 'Sherif', 'Wael', 'Hany', 'Adel', 'Ayman', 'Bassem', 'Fady', 'Mostafa', 'Sameh', 'Tamer', 'Yasser'],
    lastNames: ['Mansour', 'Hassan', 'Ibrahim', 'Said', 'Sayed', 'Aziz', 'Fahmy', 'Gamal', 'Hamdy', 'Kamal', 'Lotfy', 'Nasser', 'Rashid', 'Sabry', 'Tawfik', 'Youssef', 'Zaki', 'Abdo', 'Botros', 'Eldin'],
    cities: ['Cairo', 'Alexandria', 'Giza', 'Luxor', 'Aswan'],
  },
  {
    name: 'Israel', flag: '🇮🇱', w: 1,
    firstNames: ['Omri', 'Yuval', 'Tomer', 'Itay', 'Lior', 'Eitan', 'Ariel', 'Dor', 'Gilad', 'Noam', 'Roni', 'Shaked', 'Idan', 'Maor', 'Nadav', 'Oz', 'Raz', 'Tal', 'Uri', 'Ziv'],
    lastNames: ['Cohen', 'Levi', 'Mizrahi', 'Peretz', 'Biton', 'Avraham', 'Dahan', 'Friedman', 'Goldberg', 'Hadad', 'Katz', 'Levy', 'Malka', 'Navon', 'Ohana', 'Pinto', 'Rosen', 'Shapiro', 'Tal', 'Weiss'],
    cities: ['Tel Aviv', 'Jerusalem', 'Haifa', "Be'er Sheva"],
  },
];

export const NATIONALITY_W = NATIONALITIES.reduce((s, c) => s + c.w, 0);
