// ---------- Incoming trade offers ----------
// A few times a season, an AI team proposes a trade to the user. Offers sit
// in league.tradeOffers (an inbox shown on the dashboard) until the user
// accepts, declines, or they expire after OFFER_LIFETIME_DAYS of game time.
//
// Every offer is generated by one of a few scenario-shaped strategies below:
// a seller dumping a disgruntled star at a discount, a rebuilder flipping a
// veteran for a young player with upside, a contender chasing one of the
// user's stars, or an opportunistic lowball for a useful role player. In all
// cases the proposing team's acceptance is checked the same way it would be
// if the user proposed the mirror trade from the Trade Machine — an offer
// the AI wouldn't accept never reaches the inbox.

import { overall } from './players.js';
import { getTeam } from './league.js';
import { tradeValue, validateTrade, aiEvaluateTrade, executeTrade } from './trade.js';
import { getTeamPicks, pickValue, pickLabel, violatesStepien } from './draftPicks.js';
import { pushNews } from './save.js';

export const OFFER_LIFETIME_DAYS = 5;
const MAX_ACTIVE_OFFERS = 3;

// Drop expired offers, and any whose players have since moved on (traded,
// waived) by other means.
export function expireTradeOffers(league) {
  if (!league.tradeOffers) league.tradeOffers = [];
  if (!league.userTeamId) return; // headless leagues (sim scripts) have no user team
  const user = getTeam(league, league.userTeamId);
  league.tradeOffers = league.tradeOffers.filter((o) => {
    if (o.expiresDay <= league.dayIndex) return false;
    const from = getTeam(league, o.fromTeamId);
    if (!from) return false;
    if (!o.give.every((id) => user.roster.some((p) => p.id === id))) return false;
    if (!o.get.every((id) => from.roster.some((p) => p.id === id))) return false;
    if (!(o.givePicks || []).every((id) => league.draftPicks.find((p) => p.id === id)?.teamId === user.id)) return false;
    if (!(o.getPicks || []).every((id) => league.draftPicks.find((p) => p.id === id)?.teamId === from.id)) return false;
    return true;
  });
}

// A disgruntled AI star, shopped to the user at a discount — mirrors
// maybeShopDisgruntled's fire-sale floor (morale.js), but targets the user's
// roster instead of another AI team.
function disgruntledOffer(league, rng, user, ai) {
  const sellers = ai.filter((t) => t.roster.some((p) => p.tradeDemand && p.contract));
  if (!sellers.length) return null;
  const seller = sellers[Math.floor(rng() * sellers.length)];
  const disgruntled = seller.roster.find((p) => p.tradeDemand && p.contract);
  const shortlist = user.roster
    .filter((p) => p.contract && overall(p) < overall(disgruntled))
    .sort((a, b) => tradeValue(a, seller.strategy) - tradeValue(b, seller.strategy));
  for (let n = 1; n <= Math.min(2, shortlist.length); n++) {
    const pkg = shortlist.slice(0, n);
    const pkgIds = pkg.map((p) => p.id);
    if (!validateTrade(league, user.id, pkgIds, seller.id, [disgruntled.id]).ok) continue;
    const valueOut = tradeValue(disgruntled, seller.strategy);
    const valueIn = pkg.reduce((s, p) => s + tradeValue(p, seller.strategy), 0);
    if (valueOut > 0 && valueIn / valueOut < 0.5) continue; // even a fire sale has a floor
    return { fromTeamId: seller.id, give: pkgIds, get: [disgruntled.id] };
  }
  return null;
}

// A rebuilder flips an aging veteran for a young user player with upside —
// the kind of "kickstart the timeline" deal rebuilders chase.
function rebuilderVetOffer(league, rng, user, ai) {
  const rebuilders = [...ai.filter((t) => t.strategy === 'rebuilding')].sort(() => rng() - 0.5);
  for (const rebuilder of rebuilders) {
    const vets = rebuilder.roster
      .filter((p) => p.contract && p.age >= 29 && overall(p) >= 60 && overall(p) < 80)
      .sort((a, b) => tradeValue(b, rebuilder.strategy) - tradeValue(a, rebuilder.strategy));
    if (!vets.length) continue;
    const vet = vets[0];
    const youngsters = user.roster
      .filter((p) => p.contract && p.age <= 25 && p.potential >= overall(p) + 3)
      .sort((a, b) => tradeValue(a, rebuilder.strategy) - tradeValue(b, rebuilder.strategy));
    for (const young of youngsters) {
      if (!validateTrade(league, user.id, [young.id], rebuilder.id, [vet.id]).ok) continue;
      if (!aiEvaluateTrade(league, rebuilder.id, [young], [vet]).accept) continue;
      return { fromTeamId: rebuilder.id, give: [young.id], get: [vet.id] };
    }
  }
  return null;
}

// A contender chases one of the user's stars, packaging up depth pieces
// that pass their own greed threshold.
function contenderStarOffer(league, rng, user, ai) {
  const contenders = [...ai.filter((t) => t.strategy === 'contending')].sort(() => rng() - 0.5);
  const stars = user.roster.filter((p) => p.contract && overall(p) >= 75).sort((a, b) => overall(b) - overall(a));
  if (!stars.length) return null;
  for (const contender of contenders) {
    for (const star of stars) {
      const shortlist = contender.roster
        .filter((p) => p.contract && overall(p) < 76)
        .sort((a, b) => tradeValue(a, contender.strategy) - tradeValue(b, contender.strategy));
      for (let n = 1; n <= Math.min(2, shortlist.length); n++) {
        const pkg = shortlist.slice(0, n);
        const pkgIds = pkg.map((p) => p.id);
        if (!validateTrade(league, user.id, [star.id], contender.id, pkgIds).ok) continue;
        if (!aiEvaluateTrade(league, contender.id, [star], pkg).accept) continue;
        return { fromTeamId: contender.id, give: [star.id], get: pkgIds };
      }
    }
  }
  return null;
}

// An opportunistic lowball: an AI team tries to pry loose a useful role
// player for spare parts. Gated by an extra coin flip so it stays rare.
function lowballOffer(league, rng, user, ai) {
  if (rng() >= 0.3) return null;
  const shuffled = [...ai].sort(() => rng() - 0.5);
  const targets = user.roster
    .filter((p) => p.contract && !p.tradeDemand && overall(p) >= 60 && overall(p) <= 80)
    .sort((a, b) => overall(b) - overall(a));
  for (const team of shuffled) {
    for (const target of targets) {
      const shortlist = team.roster
        .filter((p) => p.contract && overall(p) < overall(target))
        .sort((a, b) => tradeValue(a, team.strategy) - tradeValue(b, team.strategy));
      for (let n = 1; n <= Math.min(2, shortlist.length); n++) {
        const pkg = shortlist.slice(0, n);
        const pkgIds = pkg.map((p) => p.id);
        if (!validateTrade(league, user.id, [target.id], team.id, pkgIds).ok) continue;
        if (!aiEvaluateTrade(league, team.id, [target], pkg).accept) continue;
        return { fromTeamId: team.id, give: [target.id], get: pkgIds };
      }
    }
  }
  return null;
}

// A contender, lacking immediate trade chips, dangles one of its own future
// 1st-round picks (the least valuable one it can part with under the Stepien
// rule) for a useful piece of the user's rotation — "picks for win-now help."
function contenderPickOffer(league, rng, user, ai) {
  const contenders = [...ai.filter((t) => t.strategy === 'contending')].sort(() => rng() - 0.5);
  const targets = user.roster
    .filter((p) => p.contract && !p.tradeDemand && overall(p) >= 62 && overall(p) <= 80)
    .sort((a, b) => overall(b) - overall(a));
  for (const contender of contenders) {
    const tradeableFirsts = getTeamPicks(league, contender.id)
      .filter((p) => p.round === 1 && !violatesStepien(league, contender.id, [p.id]))
      .sort((a, b) => pickValue(league, a, contender.strategy) - pickValue(league, b, contender.strategy));
    if (!tradeableFirsts.length) continue;
    const pick = tradeableFirsts[0];
    for (const target of targets) {
      if (!validateTrade(league, user.id, [target.id], contender.id, [], [], [pick.id]).ok) continue;
      if (!aiEvaluateTrade(league, contender.id, [target], [], [], [pick]).accept) continue;
      return { fromTeamId: contender.id, give: [target.id], get: [], givePicks: [], getPicks: [pick.id] };
    }
  }
  return null;
}

// A rebuilder covets future picks: it offers a useful veteran for one of the
// user's future picks (round doesn't matter — any pick sweetens the deal).
function rebuilderPickAskOffer(league, rng, user, ai) {
  const rebuilders = [...ai.filter((t) => t.strategy === 'rebuilding')].sort(() => rng() - 0.5);
  const userPicks = getTeamPicks(league, user.id);
  if (!userPicks.length) return null;
  for (const rebuilder of rebuilders) {
    const vets = rebuilder.roster
      .filter((p) => p.contract && overall(p) >= 60 && overall(p) < 75)
      .sort((a, b) => tradeValue(a, rebuilder.strategy) - tradeValue(b, rebuilder.strategy));
    if (!vets.length) continue;
    const vet = vets[0];
    for (const pick of userPicks) {
      if (!validateTrade(league, user.id, [], rebuilder.id, [vet.id], [pick.id], []).ok) continue;
      if (!aiEvaluateTrade(league, rebuilder.id, [], [vet], [pick], []).accept) continue;
      return { fromTeamId: rebuilder.id, give: [], get: [vet.id], givePicks: [pick.id], getPicks: [] };
    }
  }
  return null;
}

// Called once per sim day. Most days nothing happens; the base chance rises
// a bit when the user has disgruntled or soon-expiring valuable players, who
// naturally draw more outside interest.
export function maybeGenerateTradeOffer(league, rng) {
  if (!league.tradeOffers) league.tradeOffers = [];
  if (!league.userTeamId) return; // headless leagues (sim scripts) have no user team
  if (league.tradeOffers.length >= MAX_ACTIVE_OFFERS) return;

  const user = getTeam(league, league.userTeamId);
  let chance = 0.012;
  if (user.roster.some((p) => p.tradeDemand)) chance += 0.02;
  if (user.roster.some((p) => p.contract && p.contract.years <= 1 && overall(p) >= 68)) chance += 0.015;
  if (rng() >= chance) return;

  const ai = league.teams.filter((t) => t.id !== league.userTeamId);
  const generators = [disgruntledOffer, rebuilderVetOffer, contenderStarOffer, lowballOffer, contenderPickOffer, rebuilderPickAskOffer];
  for (let i = generators.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [generators[i], generators[j]] = [generators[j], generators[i]];
  }
  for (const gen of generators) {
    const offer = gen(league, rng, user, ai);
    if (!offer) continue;
    const from = getTeam(league, offer.fromTeamId);
    offer.id = `${league.dayIndex}-${offer.fromTeamId}-${league.tradeOffers.length}`;
    offer.createdDay = league.dayIndex;
    offer.expiresDay = league.dayIndex + OFFER_LIFETIME_DAYS;
    league.tradeOffers.push(offer);
    const giveNames = [
      ...offer.give.map((id) => user.roster.find((p) => p.id === id)?.name),
      ...(offer.givePicks || []).map((id) => pickLabel(league.draftPicks.find((p) => p.id === id))),
    ].join(', ');
    const getNames = [
      ...offer.get.map((id) => from.roster.find((p) => p.id === id)?.name),
      ...(offer.getPicks || []).map((id) => pickLabel(league.draftPicks.find((p) => p.id === id))),
    ].join(', ');
    pushNews(league, {
      day: league.dayIndex, category: 'trade', teamIds: [from.id, league.userTeamId],
      text: `📨 The ${from.name} have offered ${getNames} for your ${giveNames}.`,
    });
    return;
  }
}

// Re-validates (a roster move since the offer arrived could have made it
// illegal) and executes if still good.
export function acceptTradeOffer(league, offerId) {
  const offer = league.tradeOffers.find((o) => o.id === offerId);
  if (!offer) return { ok: false, reason: 'This offer is no longer available.' };
  const from = getTeam(league, offer.fromTeamId);
  const user = getTeam(league, league.userTeamId);
  const givePicks = offer.givePicks || [];
  const getPicks = offer.getPicks || [];
  const check = validateTrade(league, user.id, offer.give, from.id, offer.get, givePicks, getPicks);
  league.tradeOffers = league.tradeOffers.filter((o) => o.id !== offerId);
  if (!check.ok) return { ok: false, reason: `This trade is no longer valid: ${check.reason}` };
  executeTrade(league, user.id, offer.give, from.id, offer.get, givePicks, getPicks);
  return { ok: true };
}

export function declineTradeOffer(league, offerId) {
  league.tradeOffers = league.tradeOffers.filter((o) => o.id !== offerId);
}
