// ---------- Incoming trade offers ----------
// A few times a season, an AI team proposes a trade to the user. Offers sit
// in league.tradeOffers (an inbox shown on the dashboard) until the user
// accepts, declines, or they expire after OFFER_LIFETIME_DAYS of game time.
//
// Every offer is generated by one of a few scenario-shaped strategies below:
// a seller dumping a disgruntled star at a discount, a rebuilder flipping a
// veteran for a young player with upside, a contender chasing one of the
// user's stars, an opportunistic team rounding out its roster, a contender
// dangling a future pick, a rebuilder asking for one of the user's picks, or
// (when the user is rebuilding) a contender offering picks and youth instead
// of an expiring vet. In all cases the proposing team's acceptance is checked
// the same way it would be if the user proposed the mirror trade from the
// Trade Machine — an offer the AI wouldn't accept never reaches the inbox.
//
// On top of that, every offer must clear two more bars before it reaches the
// inbox:
//  - userWouldAccept: valued neutrally (the same lens the Trade Machine shows
//    the user), the package the user receives must be worth at least 85% of
//    what they're giving up. No AI valuation lens can inflate its own side to
//    get around this.
//  - fitsUserNeed: a player offered to the user shouldn't be at a position
//    the user is already stacked at, unless they're an upgrade.

import { overall } from './players.js';
import { getTeam } from './league.js';
import { tradeValue, validateTrade, aiEvaluateTrade, executeTrade } from './trade.js';
import { getTeamPicks, pickValue, pickLabel, violatesStepien } from './draftPicks.js';
import { pushNews } from './save.js';

export const OFFER_LIFETIME_DAYS = 5;
const MAX_ACTIVE_OFFERS = 3;
// After the user declines an offer, that team waits this many in-game days
// before trying again with a (necessarily different, since rosters move on)
// offer.
const REJECTION_COOLDOWN_DAYS = 21;
// A position with 2+ players at this overall or better is considered
// "stacked" — an AI offer shouldn't add to it unless it's an upgrade.
const QUALITY_OVR = 70;

// ---------- shared helpers ----------

// Neutral value of a player+pick package — the same lens the Trade Machine
// shows the user their own roster through, independent of any proposing
// team's self-serving strategy lens.
function packageValue(league, team, playerIds, pickIds) {
  const players = team.roster.filter((p) => playerIds.includes(p.id));
  const picks = pickIds.map((id) => league.draftPicks.find((p) => p.id === id)).filter(Boolean);
  return players.reduce((s, p) => s + tradeValue(p), 0) + picks.reduce((s, p) => s + pickValue(league, p), 0);
}

// The user shouldn't have to take less value than they give up just because
// an AI team wants one of their players — the package they receive must be
// worth at least 85% of what they're sending out, valued neutrally.
function userWouldAccept(league, user, from, give, get, givePicks = [], getPicks = []) {
  const valueOut = packageValue(league, user, give, givePicks);
  const valueIn = packageValue(league, from, get, getPicks);
  if (valueOut === 0) return true;
  return valueIn / valueOut >= 0.85;
}

// A position the user already has quality depth at (2+ players at
// QUALITY_OVR or better) isn't a need — a player offered there should only
// be an upgrade on what's already on the roster.
function fitsUserNeed(user, p) {
  const atPos = user.roster.filter((x) => x.pos === p.pos);
  const depth = atPos.filter((x) => overall(x) >= QUALITY_OVR).length;
  if (depth < 2) return true;
  const best = Math.max(0, ...atPos.map(overall));
  return overall(p) > best;
}

// Rebuilders are stocking up on youth and upside, not chasing aging
// veterans, no matter how good those veterans still are.
function rebuilderWouldChase(p) {
  return p.age <= 27 || p.potential >= 75;
}

function isOnCooldown(league, teamId) {
  const until = league.tradeOfferCooldowns[teamId];
  return until != null && until > league.dayIndex;
}

export function setTradeOfferCooldown(league, teamId) {
  league.tradeOfferCooldowns[teamId] = league.dayIndex + REJECTION_COOLDOWN_DAYS;
}

// A short "why are they offering this" line for opportunistic offers,
// flavored by the proposing team's strategy.
function teamFitReason(team, target) {
  if (team.strategy === 'contending') return `The ${team.name} are chasing a title and think ${target.name} can help right away.`;
  if (team.strategy === 'rebuilding') return `The ${team.name} are rebuilding and like ${target.name}'s long-term fit.`;
  return `The ${team.name} are looking to round out their roster and like what ${target.name} could add.`;
}

// Drop expired offers, and any whose players have since moved on (traded,
// waived) by other means.
export function expireTradeOffers(league) {
  if (!league.tradeOffers) league.tradeOffers = [];
  if (!league.userTeamId) return; // headless leagues (sim scripts) have no user team
  const user = getTeam(league, league.userTeamId);
  league.tradeOffers = league.tradeOffers.filter((o) => {
    if (o.expiresDay <= league.dayIndex) return false;
    const from = getTeam(league, o.fromTeamId);
    if (!from) return false;
    if (!o.give.every((id) => user.roster.some((p) => p.id === id))) return false;
    if (!o.get.every((id) => from.roster.some((p) => p.id === id))) return false;
    if (!(o.givePicks || []).every((id) => league.draftPicks.find((p) => p.id === id)?.teamId === user.id)) return false;
    if (!(o.getPicks || []).every((id) => league.draftPicks.find((p) => p.id === id)?.teamId === from.id)) return false;
    return true;
  });
}

// A disgruntled AI star, shopped to the user at a discount — mirrors
// maybeShopDisgruntled's fire-sale floor (morale.js), but targets the user's
// roster instead of another AI team.
function disgruntledOffer(league, rng, user, ai) {
  const sellers = ai.filter((t) => !isOnCooldown(league, t.id) && t.roster.some((p) => p.tradeDemand && p.contract));
  if (!sellers.length) return null;
  const seller = sellers[Math.floor(rng() * sellers.length)];
  const disgruntled = seller.roster.find((p) => p.tradeDemand && p.contract);
  if (!fitsUserNeed(user, disgruntled)) return null;
  const shortlist = user.roster
    .filter((p) => p.contract && overall(p) < overall(disgruntled))
    .sort((a, b) => tradeValue(a, seller.strategy) - tradeValue(b, seller.strategy));
  for (let n = 1; n <= Math.min(2, shortlist.length); n++) {
    const pkg = shortlist.slice(0, n);
    const pkgIds = pkg.map((p) => p.id);
    if (!validateTrade(league, user.id, pkgIds, seller.id, [disgruntled.id]).ok) continue;
    const valueOut = tradeValue(disgruntled, seller.strategy);
    const valueIn = pkg.reduce((s, p) => s + tradeValue(p, seller.strategy), 0);
    if (valueOut > 0 && valueIn / valueOut < 0.5) continue; // even a fire sale has a floor
    if (!userWouldAccept(league, user, seller, pkgIds, [disgruntled.id])) continue;
    return {
      fromTeamId: seller.id, give: pkgIds, get: [disgruntled.id],
      why: `${disgruntled.name} has demanded a trade, and the ${seller.name} are eager to move on from him.`,
    };
  }
  return null;
}

// A rebuilder flips an aging veteran for a young user player with upside —
// the kind of "kickstart the timeline" deal rebuilders chase.
function rebuilderVetOffer(league, rng, user, ai) {
  const rebuilders = [...ai.filter((t) => t.strategy === 'rebuilding' && !isOnCooldown(league, t.id))].sort(() => rng() - 0.5);
  for (const rebuilder of rebuilders) {
    const vets = rebuilder.roster
      .filter((p) => p.contract && p.age >= 29 && overall(p) >= 60 && overall(p) < 80 && fitsUserNeed(user, p))
      .sort((a, b) => tradeValue(b, rebuilder.strategy) - tradeValue(a, rebuilder.strategy));
    if (!vets.length) continue;
    const vet = vets[0];
    const youngsters = user.roster
      .filter((p) => p.contract && p.age <= 25 && p.potential >= overall(p) + 3)
      .sort((a, b) => tradeValue(a, rebuilder.strategy) - tradeValue(b, rebuilder.strategy));
    for (const young of youngsters) {
      if (!validateTrade(league, user.id, [young.id], rebuilder.id, [vet.id]).ok) continue;
      if (!aiEvaluateTrade(league, rebuilder.id, [young], [vet]).accept) continue;
      if (!userWouldAccept(league, user, rebuilder, [young.id], [vet.id])) continue;
      return {
        fromTeamId: rebuilder.id, give: [young.id], get: [vet.id],
        why: `The ${rebuilder.name} are rebuilding and want to flip ${vet.name} for a younger long-term piece.`,
      };
    }
  }
  return null;
}

// A contender chases one of the user's stars, packaging up depth pieces
// that pass their own greed threshold.
function contenderStarOffer(league, rng, user, ai) {
  const contenders = [...ai.filter((t) => t.strategy === 'contending' && !isOnCooldown(league, t.id))].sort(() => rng() - 0.5);
  const stars = user.roster.filter((p) => p.contract && overall(p) >= 75).sort((a, b) => overall(b) - overall(a));
  if (!stars.length) return null;
  for (const contender of contenders) {
    for (const star of stars) {
      const shortlist = contender.roster
        .filter((p) => p.contract && overall(p) < 76 && fitsUserNeed(user, p))
        .sort((a, b) => tradeValue(a, contender.strategy) - tradeValue(b, contender.strategy));
      for (let n = 1; n <= Math.min(2, shortlist.length); n++) {
        const pkg = shortlist.slice(0, n);
        const pkgIds = pkg.map((p) => p.id);
        if (!validateTrade(league, user.id, [star.id], contender.id, pkgIds).ok) continue;
        if (!aiEvaluateTrade(league, contender.id, [star], pkg).accept) continue;
        if (!userWouldAccept(league, user, contender, [star.id], pkgIds)) continue;
        return {
          fromTeamId: contender.id, give: [star.id], get: pkgIds,
          why: `The ${contender.name} are chasing a title and want your ${star.name}.`,
        };
      }
    }
  }
  return null;
}

// An opportunistic offer: an AI team looking to round out its roster targets
// a useful player and puts together a package its own front office likes.
function lowballOffer(league, rng, user, ai) {
  if (rng() >= 0.3) return null;
  const shuffled = [...ai.filter((t) => !isOnCooldown(league, t.id))].sort(() => rng() - 0.5);
  const targets = user.roster
    .filter((p) => p.contract && !p.tradeDemand && overall(p) >= 60 && overall(p) <= 80)
    .sort((a, b) => overall(b) - overall(a));
  for (const team of shuffled) {
    for (const target of targets) {
      if (team.strategy === 'rebuilding' && !rebuilderWouldChase(target)) continue;
      const shortlist = team.roster
        .filter((p) => p.contract && overall(p) < overall(target) && fitsUserNeed(user, p))
        .sort((a, b) => tradeValue(a, team.strategy) - tradeValue(b, team.strategy));
      for (let n = 1; n <= Math.min(2, shortlist.length); n++) {
        const pkg = shortlist.slice(0, n);
        const pkgIds = pkg.map((p) => p.id);
        if (!validateTrade(league, user.id, [target.id], team.id, pkgIds).ok) continue;
        if (!aiEvaluateTrade(league, team.id, [target], pkg).accept) continue;
        if (!userWouldAccept(league, user, team, [target.id], pkgIds)) continue;
        return {
          fromTeamId: team.id, give: [target.id], get: pkgIds,
          why: teamFitReason(team, target),
        };
      }
    }
  }
  return null;
}

// A contender, lacking immediate trade chips, dangles one of its own future
// 1st-round picks (the least valuable one it can part with under the Stepien
// rule) for a useful piece of the user's rotation — "picks for win-now help."
function contenderPickOffer(league, rng, user, ai) {
  const contenders = [...ai.filter((t) => t.strategy === 'contending' && !isOnCooldown(league, t.id))].sort(() => rng() - 0.5);
  const targets = user.roster
    .filter((p) => p.contract && !p.tradeDemand && overall(p) >= 62 && overall(p) <= 80)
    .sort((a, b) => overall(b) - overall(a));
  for (const contender of contenders) {
    const tradeableFirsts = getTeamPicks(league, contender.id)
      .filter((p) => p.round === 1 && !violatesStepien(league, contender.id, [p.id]))
      .sort((a, b) => pickValue(league, a, contender.strategy) - pickValue(league, b, contender.strategy));
    if (!tradeableFirsts.length) continue;
    const pick = tradeableFirsts[0];
    for (const target of targets) {
      if (!validateTrade(league, user.id, [target.id], contender.id, [], [], [pick.id]).ok) continue;
      if (!aiEvaluateTrade(league, contender.id, [target], [], [], [pick]).accept) continue;
      if (!userWouldAccept(league, user, contender, [target.id], [], [], [pick.id])) continue;
      return {
        fromTeamId: contender.id, give: [target.id], get: [], givePicks: [], getPicks: [pick.id],
        why: `The ${contender.name} are buying for a title push and will pay with a future pick for ${target.name}.`,
      };
    }
  }
  return null;
}

// A rebuilder covets future picks: it offers a useful veteran for one of the
// user's future picks (round doesn't matter — any pick sweetens the deal).
function rebuilderPickAskOffer(league, rng, user, ai) {
  const rebuilders = [...ai.filter((t) => t.strategy === 'rebuilding' && !isOnCooldown(league, t.id))].sort(() => rng() - 0.5);
  const userPicks = getTeamPicks(league, user.id);
  if (!userPicks.length) return null;
  for (const rebuilder of rebuilders) {
    const vets = rebuilder.roster
      .filter((p) => p.contract && overall(p) >= 60 && overall(p) < 75 && fitsUserNeed(user, p))
      .sort((a, b) => tradeValue(a, rebuilder.strategy) - tradeValue(b, rebuilder.strategy));
    if (!vets.length) continue;
    const vet = vets[0];
    for (const pick of userPicks) {
      if (!validateTrade(league, user.id, [], rebuilder.id, [vet.id], [pick.id], []).ok) continue;
      if (!aiEvaluateTrade(league, rebuilder.id, [], [vet], [pick], []).accept) continue;
      if (!userWouldAccept(league, user, rebuilder, [], [vet.id], [pick.id], [])) continue;
      return {
        fromTeamId: rebuilder.id, give: [], get: [vet.id], givePicks: [pick.id], getPicks: [],
        why: `The ${rebuilder.name} are rebuilding and want to add to their draft capital — they'll send ${vet.name} for one of your future picks.`,
      };
    }
  }
  return null;
}

// If the user is rebuilding, contenders shouldn't dangle expiring vets — they
// pay for a useful veteran with a young rotation player, a future 1st, or
// both, the kind of package that actually helps a rebuild.
function contenderRebuildOffer(league, rng, user, ai) {
  if (user.strategy !== 'rebuilding') return null;
  const contenders = [...ai.filter((t) => t.strategy === 'contending' && !isOnCooldown(league, t.id))].sort(() => rng() - 0.5);
  const targets = user.roster
    .filter((p) => p.contract && !p.tradeDemand && overall(p) >= 68)
    .sort((a, b) => overall(b) - overall(a));
  for (const contender of contenders) {
    const youngsters = contender.roster
      .filter((p) => p.contract && p.age <= 24 && overall(p) < 72 && fitsUserNeed(user, p))
      .sort((a, b) => tradeValue(b, contender.strategy) - tradeValue(a, contender.strategy));
    const firsts = getTeamPicks(league, contender.id)
      .filter((p) => p.round === 1 && !violatesStepien(league, contender.id, [p.id]))
      .sort((a, b) => pickValue(league, a, contender.strategy) - pickValue(league, b, contender.strategy));
    for (const target of targets) {
      const combos = [];
      if (youngsters.length && firsts.length) combos.push({ young: youngsters[0], pick: firsts[0] });
      if (firsts.length) combos.push({ young: null, pick: firsts[0] });
      if (youngsters.length) combos.push({ young: youngsters[0], pick: null });
      for (const { young, pick } of combos) {
        const getIds = young ? [young.id] : [];
        const getPicks = pick ? [pick.id] : [];
        if (!validateTrade(league, user.id, [target.id], contender.id, getIds, [], getPicks).ok) continue;
        if (!aiEvaluateTrade(league, contender.id, [target], young ? [young] : [], [], pick ? [pick] : []).accept) continue;
        if (!userWouldAccept(league, user, contender, [target.id], getIds, [], getPicks)) continue;
        const piece = young && pick ? `a young rotation player and a future pick` : pick ? `a future pick` : `a young rotation player`;
        return {
          fromTeamId: contender.id, give: [target.id], get: getIds, givePicks: [], getPicks,
          why: `The ${contender.name} are contending and want ${target.name} to help right now — they're offering ${piece} rather than an expiring vet.`,
        };
      }
    }
  }
  return null;
}

// Called once per sim day. Most days nothing happens; the base chance rises
// a bit when the user has disgruntled or soon-expiring valuable players, who
// naturally draw more outside interest.
export function maybeGenerateTradeOffer(league, rng) {
  if (!league.tradeOffers) league.tradeOffers = [];
  if (!league.userTeamId) return; // headless leagues (sim scripts) have no user team
  if (league.tradeOffers.length >= MAX_ACTIVE_OFFERS) return;

  const user = getTeam(league, league.userTeamId);
  if (!user) return; // some headless scripts use a non-matching sentinel id instead of null
  let chance = 0.012;
  if (user.roster.some((p) => p.tradeDemand)) chance += 0.02;
  if (user.roster.some((p) => p.contract && p.contract.years <= 1 && overall(p) >= 68)) chance += 0.015;
  if (rng() >= chance) return;

  const ai = league.teams.filter((t) => t.id !== league.userTeamId);
  const generators = [disgruntledOffer, rebuilderVetOffer, contenderStarOffer, lowballOffer, contenderPickOffer, rebuilderPickAskOffer, contenderRebuildOffer];
  for (let i = generators.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [generators[i], generators[j]] = [generators[j], generators[i]];
  }
  for (const gen of generators) {
    const offer = gen(league, rng, user, ai);
    if (!offer) continue;
    const from = getTeam(league, offer.fromTeamId);
    offer.id = `${league.dayIndex}-${offer.fromTeamId}-${league.tradeOffers.length}`;
    offer.createdDay = league.dayIndex;
    offer.expiresDay = league.dayIndex + OFFER_LIFETIME_DAYS;
    league.tradeOffers.push(offer);
    const giveNames = [
      ...offer.give.map((id) => user.roster.find((p) => p.id === id)?.name),
      ...(offer.givePicks || []).map((id) => pickLabel(league.draftPicks.find((p) => p.id === id))),
    ].join(', ');
    const getNames = [
      ...offer.get.map((id) => from.roster.find((p) => p.id === id)?.name),
      ...(offer.getPicks || []).map((id) => pickLabel(league.draftPicks.find((p) => p.id === id))),
    ].join(', ');
    pushNews(league, {
      day: league.dayIndex, category: 'trade', teamIds: [from.id, league.userTeamId],
      text: `📨 The ${from.name} have offered ${getNames} for your ${giveNames}. ${offer.why || ''}`.trim(),
    });
    return;
  }
}

// Re-validates (a roster move since the offer arrived could have made it
// illegal) and executes if still good.
export function acceptTradeOffer(league, offerId) {
  const offer = league.tradeOffers.find((o) => o.id === offerId);
  if (!offer) return { ok: false, reason: 'This offer is no longer available.' };
  const from = getTeam(league, offer.fromTeamId);
  const user = getTeam(league, league.userTeamId);
  const givePicks = offer.givePicks || [];
  const getPicks = offer.getPicks || [];
  const check = validateTrade(league, user.id, offer.give, from.id, offer.get, givePicks, getPicks);
  league.tradeOffers = league.tradeOffers.filter((o) => o.id !== offerId);
  if (!check.ok) return { ok: false, reason: `This trade is no longer valid: ${check.reason}` };
  executeTrade(league, user.id, offer.give, from.id, offer.get, givePicks, getPicks);
  return { ok: true };
}

// Declining doesn't just dismiss the offer — that team backs off for a
// while before trying again with a different offer.
export function declineTradeOffer(league, offerId) {
  const offer = league.tradeOffers.find((o) => o.id === offerId);
  if (offer) setTradeOfferCooldown(league, offer.fromTeamId);
  league.tradeOffers = league.tradeOffers.filter((o) => o.id !== offerId);
}
